name: Deploy FrontEnd to S3 and invalidate CloudFront

on:
  push:
    branchs:
    - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.PROD_DEPLOY_ROLE }}
          role-session-name: github-actions

      - name: copy files to S3 bucket
        run: aws s3 sync ./cloud-site s3://tayztech.com

# Job to configure cloudFront invalidation 
      - name: Invalidate files from CloudFront's Cache
        run: aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION" --paths "$PATHS"
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/index.html"
          AWS_REGION: "us-east-1"

